### ISSUE TITLE
crash in android-studio

### ISSUE THREAD

**Issue by kingrukawa** [axaluss/power-mode-intellij-plugin#20] opened 2017-03-06 02:37 UTC
android-studio version:2.3
plugin crash 
![image](https://cloud.githubusercontent.com/assets/5400325/23594920/d65fa054-0258-11e7-8e3a-45b8a169d817.png)

**Comment by sibuty** [comment] 2017-03-06 08:29
I have this problem too.

**Comment by sibuty** [comment] 2017-03-06 08:32
Stable version is 2.8.12. :)

**Comment by axaluss** [comment] 2017-03-06 18:23
java.lang.NoClassDefFoundError: javafx/scene/media/MediaException 

i wasn't able to reproduce the error on
Android Studio 2.3
Build #AI-162.3764568, built on February 24, 2017
JRE: 1.8.0_121-b13 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

And neither on:

IntelliJ IDEA 2016.3.4
Build #IU-163.12024.16, built on January 31, 2017
Subscription is active until February 28, 2018
JRE: 1.8.0_112-release-408-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o


java.lang.NoClassDefFoundError: javafx/scene/media/MediaException looks like there is javafx missing on the java install/classpath. but i dont know why this is missing in your install but not in mine.

Any ideas?

**Comment by axaluss** [comment] 2017-03-06 20:34
fixed in 2.12.12
This wasnt reproducibly using plugin run mode. 
By default intellij does not include jfxrt in its own jre/jdk classpath.
To be able to play music you have to add jfxrt to your classpath or make intellij use oracle java or install the ubuntu package 'openjfx'.

**Closed by axaluss** 2017-03-06 20:34 UTC
Labels: bug

**Comment by kingrukawa** [comment] 2017-03-07 01:19
good job,man.
tks a lot
